### ISSUE TITLE
"includesGravity" vs "includeGravity"

### ISSUE THREAD

**Issue by Honry** [w3c/accelerometer#12]
>readonly attribute boolean includesGravity;

>boolean includeGravity = true;

The includeGravity parameter is not consistent. Is it intentional design?

**Comment by alexshalamov** [comment]
Yes that is intentional.

Accelerometer.includesGravity tells whether sensor reading includes gravity.
AccelerometerOptions.includeGravity is a parameter that tells to include or exclude gravity values from sensor reading values. Similar patterns are used in other APIs e.g. Events.  Input `boolean canBubble => Event.bubbles`.

**Comment by Honry** [comment]
@alexshalamov , thanks for your clarification, close it.
