### ISSUE TITLE
Duplicate definition of LocalCoordinateSystem

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/accelerometer#41]
The enum `LocalCoordinateSystem` is [defined in each of the motion sensor spec](https://dontcallmedom.github.io/webidlpedia/?idlname=LocalCoordinateSystem) - it should be defined just once, and referenced from other specs.

**Comment by rakuco** [comment]
I've just submitted https://github.com/w3c/web-platform-tests/pull/9949 to update web-platform-tests; https://github.com/w3c/web-platform-tests/pull/9948 updates the Gyroscope spec (w3c/gyroscope#34).

There have been no updates to the Magnetometer and Orientation Sensor specs, it's not clear if it's intentional.

**Comment by anssiko** [comment]
@rakuco, thanks for the catch, now fixed.
